/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    reports: Report;
    scores: Score;
    shooters: Shooter;
    classifiers: Classifier;
    rechhfs: Rechhf;
    matches: Match;
    matchscores: Matchscore;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    reports: ReportsSelect<false> | ReportsSelect<true>;
    scores: ScoresSelect<false> | ScoresSelect<true>;
    shooters: ShootersSelect<false> | ShootersSelect<true>;
    classifiers: ClassifiersSelect<false> | ClassifiersSelect<true>;
    rechhfs: RechhfsSelect<false> | RechhfsSelect<true>;
    matches: MatchesSelect<false> | MatchesSelect<true>;
    matchscores: MatchscoresSelect<false> | MatchscoresSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  role: 'admin' | 'moderator' | 'user';
  /**
   * USPSA member number for linking to shooter profile
   */
  memberNumber?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports".
 */
export interface Report {
  id: string;
  /**
   * Score date
   */
  sd?: string | null;
  memberNumber: string;
  division?: string | null;
  classifier?: string | null;
  /**
   * Hit factor
   */
  hf?: number | null;
  recPercent?: number | null;
  percent?: number | null;
  clubid?: string | null;
  club_name?: string | null;
  matchName?: string | null;
  /**
   * URL to source/evidence
   */
  url?: string | null;
  reason: 'wrong_score' | 'duplicate' | 'incorrect_member' | 'suspicious' | 'other';
  /**
   * Additional details
   */
  comment?: string | null;
  type?: ('score' | 'shooter' | 'match') | null;
  /**
   * ID of the target document
   */
  targetId?: string | null;
  /**
   * Report has been reviewed/resolved
   */
  done?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scores".
 */
export interface Score {
  id: string;
  /**
   * Shooter's member number
   */
  memberNumber: string;
  /**
   * Classifier code (e.g., '99-11'). Empty for major match scores.
   */
  classifier?: string | null;
  /**
   * Division code (e.g., 'co', 'opn', 'prod')
   */
  division: string;
  /**
   * Compound key: classifier:division
   */
  classifierDivision?: string | null;
  /**
   * Compound key: memberNumber:division
   */
  memberNumberDivision?: string | null;
  /**
   * Hit Factor achieved
   */
  hf: number;
  /**
   * Percentage at time of score
   */
  percent?: number | null;
  /**
   * Current HHF at time of retrieval
   */
  curHHF?: number | null;
  /**
   * Recommended HHF
   */
  recHHF?: number | null;
  /**
   * Old/legacy HHF
   */
  oldHHF?: number | null;
  /**
   * HFU (Hit Factor) HHF
   */
  hfuHF?: number | null;
  /**
   * Current percentage (computed from hf/curHHF)
   */
  curPercent?: number | null;
  /**
   * Recommended percentage (computed from hf/recHHF)
   */
  recPercent?: number | null;
  /**
   * Old percentage (computed from hf/oldHHF)
   */
  oldPercent?: number | null;
  /**
   * Score code/identifier
   */
  code?: string | null;
  /**
   * Source of the score data
   */
  source?: string | null;
  /**
   * Club identifier
   */
  clubid?: string | null;
  /**
   * Club name
   */
  club_name?: string | null;
  /**
   * Club code
   */
  clubCode?: string | null;
  /**
   * Score date
   */
  sd?: string | null;
  /**
   * Upload date
   */
  upload?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  shooterFullName?: string | null;
  /**
   * Classification letter (GM, M, A, B, C, D, U)
   */
  class?: string | null;
  /**
   * Current classification
   */
  curClass?: string | null;
  /**
   * Age category
   */
  age?: string | null;
  /**
   * Lady category
   */
  lady?: boolean | null;
  /**
   * Military category
   */
  mil?: boolean | null;
  /**
   * Law enforcement category
   */
  law?: boolean | null;
  /**
   * Foreign shooter
   */
  foreign?: boolean | null;
  matchName?: string | null;
  matchId?: string | null;
  matchLevel?: string | null;
  templateName?: string | null;
  stageName?: string | null;
  stageNumber?: number | null;
  /**
   * A zone hits
   */
  a?: number | null;
  /**
   * B zone hits
   */
  b?: number | null;
  /**
   * C zone hits
   */
  c?: number | null;
  /**
   * D zone hits
   */
  d?: number | null;
  /**
   * Misses
   */
  m?: number | null;
  /**
   * No-shoots
   */
  ns?: number | null;
  /**
   * Non-penalty misses
   */
  npm?: number | null;
  /**
   * Did not finish
   */
  dnf?: boolean | null;
  /**
   * Disqualified
   */
  dq?: boolean | null;
  /**
   * Stage time in seconds
   */
  time?: number | null;
  /**
   * Total points scored
   */
  points?: number | null;
  /**
   * Penalty points
   */
  penalties?: number | null;
  /**
   * Number of penalties
   */
  penaltyCount?: number | null;
  /**
   * Procedural penalties
   */
  procedurals?: number | null;
  /**
   * String times for steel challenge
   */
  strings?:
    | {
        time?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Raw string times data
   */
  stringTimes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Number of dropped strings
   */
  drops?: number | null;
  /**
   * Flagged as bad/invalid score
   */
  bad?: boolean | null;
  /**
   * Reason score is invalid
   */
  invalidReason?: string | null;
  /**
   * Flagged for review
   */
  flagged?: boolean | null;
  /**
   * Reason for flag
   */
  flagReason?: string | null;
  /**
   * Internal unique identifier
   */
  internalId?: string | null;
  /**
   * Hash for deduplication
   */
  hash?: string | null;
  /**
   * SCSA peak time
   */
  scsaPeak?: number | null;
  /**
   * SCSA average time
   */
  scsaAverage?: number | null;
  /**
   * Sport identifier (uspsa, scsa, hfu, pcsl)
   */
  sport?: string | null;
  /**
   * Geographic region
   */
  region?: string | null;
  /**
   * State/province
   */
  state?: string | null;
  /**
   * Country
   */
  country?: string | null;
  /**
   * Last modified timestamp
   */
  modified?: string | null;
  /**
   * Original ID from source system
   */
  originalId?: string | null;
  /**
   * PractiScore shooter ID
   */
  psShooterId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shooters".
 */
export interface Shooter {
  id: string;
  memberNumber: string;
  /**
   * Internal member ID
   */
  memberId?: string | null;
  name?: string | null;
  division: string;
  memberNumberDivision?: string | null;
  /**
   * Current classification letter
   */
  class?: string | null;
  /**
   * USPSA HQ classification
   */
  hqClass?: string | null;
  /**
   * HQ class numeric rank
   */
  hqClassRank?: number | null;
  /**
   * Current recommended percent (uncapped)
   */
  reclassificationsRecPercentUncappedCurrent?: number | null;
  /**
   * High recommended percent (uncapped)
   */
  reclassificationsRecPercentUncappedHigh?: number | null;
  /**
   * History of recommended percentages
   */
  reclassificationsRecPercentHistory?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Current percent from majors only
   */
  reclassificationsMajorsCurrent?: number | null;
  /**
   * History of majors-only percentages
   */
  reclassificationsMajorsHistory?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Current percent from classifiers only
   */
  reclassificationsClassifiersCurrent?: number | null;
  /**
   * History of classifiers-only percentages
   */
  reclassificationsClassifiersHistory?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Current recommended class (uncapped)
   */
  recUncappedClassCurrent?: string | null;
  recUncappedClassCurrentRank?: number | null;
  /**
   * High recommended class (uncapped)
   */
  recUncappedClassHigh?: string | null;
  recUncappedClassHighRank?: number | null;
  /**
   * Age of classification data
   */
  age?: number | null;
  /**
   * Age metric 1
   */
  age1?: number | null;
  /**
   * ELO rating
   */
  elo?: number | null;
  /**
   * Current HQ percent
   */
  current?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "classifiers".
 */
export interface Classifier {
  id: string;
  classifier: string;
  division: string;
  classifierDivision?: string | null;
  name?: string | null;
  /**
   * Total number of runs
   */
  runs?: number | null;
  /**
   * Runs in the last year
   */
  lastYearRuns?: number | null;
  /**
   * Current HHF
   */
  hhf?: number | null;
  /**
   * Previous HHF
   */
  prevHHF?: number | null;
  inverse95RecPercentPercentile?: number | null;
  inverse85RecPercentPercentile?: number | null;
  inverse75RecPercentPercentile?: number | null;
  inverse60RecPercentPercentile?: number | null;
  inverse40RecPercentPercentile?: number | null;
  inverse95CurPercentPercentile?: number | null;
  inverse85CurPercentPercentile?: number | null;
  inverse75CurPercentPercentile?: number | null;
  inverse60CurPercentPercentile?: number | null;
  inverse40CurPercentPercentile?: number | null;
  /**
   * Runs with ELO data
   */
  eloRuns?: number | null;
  /**
   * ELO correlation coefficient
   */
  eloCorrelation?: number | null;
  /**
   * Runs with majors data
   */
  majorsRuns?: number | null;
  /**
   * Majors correlation coefficient
   */
  majorsCorrelation?: number | null;
  /**
   * Classification correlation coefficient
   */
  classificationCorrelation?: number | null;
  runsTotalsLegitGM?: number | null;
  runsTotalsLegitM?: number | null;
  runsTotalsLegitA?: number | null;
  runsTotalsLegitB?: number | null;
  runsTotalsLegitC?: number | null;
  runsTotalsLegitD?: number | null;
  runsTotalsLegitHundo?: number | null;
  runsTotalsLegitTotal?: number | null;
  clubsCount?: number | null;
  /**
   * Clubs that have run this classifier
   */
  clubs?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Historical HHF values
   */
  hhfs?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  top1PercentilePercent?: number | null;
  top1PercentileCurPercent?: number | null;
  top1PercentileHF?: number | null;
  top2PercentilePercent?: number | null;
  top2PercentileCurPercent?: number | null;
  top2PercentileHF?: number | null;
  top5PercentilePercent?: number | null;
  top5PercentileCurPercent?: number | null;
  top5PercentileHF?: number | null;
  top10CurPercentAvg?: number | null;
  updated?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rechhfs".
 */
export interface Rechhf {
  id: string;
  classifier: string;
  division: string;
  classifierDivision?: string | null;
  /**
   * Legacy/old HHF
   */
  oldHHF?: number | null;
  /**
   * Current USPSA HQ HHF
   */
  curHHF?: number | null;
  /**
   * Recommended HHF
   */
  recHHF?: number | null;
  /**
   * Weibull shape parameter (k)
   */
  k?: number | null;
  /**
   * Weibull scale parameter (lambda)
   */
  lambda?: number | null;
  /**
   * Weibull 1% HHF estimate
   */
  wbl1HHF?: number | null;
  /**
   * Weibull 3% HHF estimate
   */
  wbl3HHF?: number | null;
  /**
   * Weibull 5% HHF estimate
   */
  wbl5HHF?: number | null;
  /**
   * Weibull 15% HHF estimate
   */
  wbl15HHF?: number | null;
  kurtosis?: number | null;
  skewness?: number | null;
  meanSquaredError?: number | null;
  meanAbsoluteError?: number | null;
  superMeanSquaredError?: number | null;
  superMeanAbsoluteError?: number | null;
  maxError?: number | null;
  /**
   * Production 10-round HHF
   */
  prod10HHF?: number | null;
  /**
   * Production 10-round major HHF
   */
  prod10MajorHHF?: number | null;
  /**
   * Production 15-round HHF
   */
  prod15HHF?: number | null;
  /**
   * Limited Optics HHF
   */
  loHHF?: number | null;
  /**
   * LO+CO combined HHF
   */
  locoHHF?: number | null;
  /**
   * LO+CO major HHF
   */
  locoMajorHHF?: number | null;
  /**
   * Carry Optics HHF
   */
  coHHF?: number | null;
  /**
   * Open HHF
   */
  opnHHF?: number | null;
  /**
   * Limited HHF
   */
  ltdHHF?: number | null;
  /**
   * Schizo HHF (L10)
   */
  schizoHHF?: number | null;
  /**
   * Prophecy HHF (L10)
   */
  prophecyHHF?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matches".
 */
export interface Match {
  id: number;
  /**
   * PractiScore match UUID
   */
  uuid: string;
  name?: string | null;
  /**
   * Match type (e.g., uspsa_p)
   */
  type?: string | null;
  /**
   * Match subtype
   */
  subType?: string | null;
  /**
   * Template name
   */
  templateName?: string | null;
  /**
   * Match date string
   */
  date?: string | null;
  /**
   * Last updated timestamp
   */
  updated?: string | null;
  /**
   * Creation timestamp
   */
  created?: string | null;
  /**
   * When match metadata was fetched
   */
  fetched?: string | null;
  /**
   * When scores were processed/uploaded
   */
  uploaded?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matchscores".
 */
export interface Matchscore {
  id: string;
  /**
   * Match UUID
   */
  upload: string;
  division: string;
  /**
   * Compound: upload:division
   */
  uploadDivision?: string | null;
  memberNumber: string;
  /**
   * Original member number before normalization
   */
  originalMemberNumber?: string | null;
  memberNumberDivision?: string | null;
  shooterFullName?: string | null;
  date: string;
  /**
   * Match percentage
   */
  matchPercent?: number | null;
  /**
   * Percent of possible points
   */
  percentOfPossible?: number | null;
  /**
   * Shooter rec percent at time of match
   */
  shooterRecPercentHistorical?: number | null;
  shooterRecPercentHistoricalHigh?: number | null;
  shooterRecPercentHistoricalAge?: number | null;
  shooterMajorsPercentHistorical?: number | null;
  shooterMajorsPercentHistoricalHigh?: number | null;
  shooterMajorsPercentHistoricalAge?: number | null;
  shooterClassifiersPercentHistorical?: number | null;
  shooterClassifiersPercentHistoricalHigh?: number | null;
  shooterClassifiersPercentHistoricalAge?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'reports';
        value: string | Report;
      } | null)
    | ({
        relationTo: 'scores';
        value: string | Score;
      } | null)
    | ({
        relationTo: 'shooters';
        value: string | Shooter;
      } | null)
    | ({
        relationTo: 'classifiers';
        value: string | Classifier;
      } | null)
    | ({
        relationTo: 'rechhfs';
        value: string | Rechhf;
      } | null)
    | ({
        relationTo: 'matches';
        value: number | Match;
      } | null)
    | ({
        relationTo: 'matchscores';
        value: string | Matchscore;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  memberNumber?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports_select".
 */
export interface ReportsSelect<T extends boolean = true> {
  sd?: T;
  memberNumber?: T;
  division?: T;
  classifier?: T;
  hf?: T;
  recPercent?: T;
  percent?: T;
  clubid?: T;
  club_name?: T;
  matchName?: T;
  url?: T;
  reason?: T;
  comment?: T;
  type?: T;
  targetId?: T;
  done?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scores_select".
 */
export interface ScoresSelect<T extends boolean = true> {
  memberNumber?: T;
  classifier?: T;
  division?: T;
  classifierDivision?: T;
  memberNumberDivision?: T;
  hf?: T;
  percent?: T;
  curHHF?: T;
  recHHF?: T;
  oldHHF?: T;
  hfuHF?: T;
  curPercent?: T;
  recPercent?: T;
  oldPercent?: T;
  code?: T;
  source?: T;
  clubid?: T;
  club_name?: T;
  clubCode?: T;
  sd?: T;
  upload?: T;
  firstName?: T;
  lastName?: T;
  shooterFullName?: T;
  class?: T;
  curClass?: T;
  age?: T;
  lady?: T;
  mil?: T;
  law?: T;
  foreign?: T;
  matchName?: T;
  matchId?: T;
  matchLevel?: T;
  templateName?: T;
  stageName?: T;
  stageNumber?: T;
  a?: T;
  b?: T;
  c?: T;
  d?: T;
  m?: T;
  ns?: T;
  npm?: T;
  dnf?: T;
  dq?: T;
  time?: T;
  points?: T;
  penalties?: T;
  penaltyCount?: T;
  procedurals?: T;
  strings?:
    | T
    | {
        time?: T;
        id?: T;
      };
  stringTimes?: T;
  drops?: T;
  bad?: T;
  invalidReason?: T;
  flagged?: T;
  flagReason?: T;
  internalId?: T;
  hash?: T;
  scsaPeak?: T;
  scsaAverage?: T;
  sport?: T;
  region?: T;
  state?: T;
  country?: T;
  modified?: T;
  originalId?: T;
  psShooterId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shooters_select".
 */
export interface ShootersSelect<T extends boolean = true> {
  memberNumber?: T;
  memberId?: T;
  name?: T;
  division?: T;
  memberNumberDivision?: T;
  class?: T;
  hqClass?: T;
  hqClassRank?: T;
  reclassificationsRecPercentUncappedCurrent?: T;
  reclassificationsRecPercentUncappedHigh?: T;
  reclassificationsRecPercentHistory?: T;
  reclassificationsMajorsCurrent?: T;
  reclassificationsMajorsHistory?: T;
  reclassificationsClassifiersCurrent?: T;
  reclassificationsClassifiersHistory?: T;
  recUncappedClassCurrent?: T;
  recUncappedClassCurrentRank?: T;
  recUncappedClassHigh?: T;
  recUncappedClassHighRank?: T;
  age?: T;
  age1?: T;
  elo?: T;
  current?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "classifiers_select".
 */
export interface ClassifiersSelect<T extends boolean = true> {
  classifier?: T;
  division?: T;
  classifierDivision?: T;
  name?: T;
  runs?: T;
  lastYearRuns?: T;
  hhf?: T;
  prevHHF?: T;
  inverse95RecPercentPercentile?: T;
  inverse85RecPercentPercentile?: T;
  inverse75RecPercentPercentile?: T;
  inverse60RecPercentPercentile?: T;
  inverse40RecPercentPercentile?: T;
  inverse95CurPercentPercentile?: T;
  inverse85CurPercentPercentile?: T;
  inverse75CurPercentPercentile?: T;
  inverse60CurPercentPercentile?: T;
  inverse40CurPercentPercentile?: T;
  eloRuns?: T;
  eloCorrelation?: T;
  majorsRuns?: T;
  majorsCorrelation?: T;
  classificationCorrelation?: T;
  runsTotalsLegitGM?: T;
  runsTotalsLegitM?: T;
  runsTotalsLegitA?: T;
  runsTotalsLegitB?: T;
  runsTotalsLegitC?: T;
  runsTotalsLegitD?: T;
  runsTotalsLegitHundo?: T;
  runsTotalsLegitTotal?: T;
  clubsCount?: T;
  clubs?: T;
  hhfs?: T;
  top1PercentilePercent?: T;
  top1PercentileCurPercent?: T;
  top1PercentileHF?: T;
  top2PercentilePercent?: T;
  top2PercentileCurPercent?: T;
  top2PercentileHF?: T;
  top5PercentilePercent?: T;
  top5PercentileCurPercent?: T;
  top5PercentileHF?: T;
  top10CurPercentAvg?: T;
  updated?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rechhfs_select".
 */
export interface RechhfsSelect<T extends boolean = true> {
  classifier?: T;
  division?: T;
  classifierDivision?: T;
  oldHHF?: T;
  curHHF?: T;
  recHHF?: T;
  k?: T;
  lambda?: T;
  wbl1HHF?: T;
  wbl3HHF?: T;
  wbl5HHF?: T;
  wbl15HHF?: T;
  kurtosis?: T;
  skewness?: T;
  meanSquaredError?: T;
  meanAbsoluteError?: T;
  superMeanSquaredError?: T;
  superMeanAbsoluteError?: T;
  maxError?: T;
  prod10HHF?: T;
  prod10MajorHHF?: T;
  prod15HHF?: T;
  loHHF?: T;
  locoHHF?: T;
  locoMajorHHF?: T;
  coHHF?: T;
  opnHHF?: T;
  ltdHHF?: T;
  schizoHHF?: T;
  prophecyHHF?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matches_select".
 */
export interface MatchesSelect<T extends boolean = true> {
  id?: T;
  uuid?: T;
  name?: T;
  type?: T;
  subType?: T;
  templateName?: T;
  date?: T;
  updated?: T;
  created?: T;
  fetched?: T;
  uploaded?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matchscores_select".
 */
export interface MatchscoresSelect<T extends boolean = true> {
  upload?: T;
  division?: T;
  uploadDivision?: T;
  memberNumber?: T;
  originalMemberNumber?: T;
  memberNumberDivision?: T;
  shooterFullName?: T;
  date?: T;
  matchPercent?: T;
  percentOfPossible?: T;
  shooterRecPercentHistorical?: T;
  shooterRecPercentHistoricalHigh?: T;
  shooterRecPercentHistoricalAge?: T;
  shooterMajorsPercentHistorical?: T;
  shooterMajorsPercentHistoricalHigh?: T;
  shooterMajorsPercentHistoricalAge?: T;
  shooterClassifiersPercentHistorical?: T;
  shooterClassifiersPercentHistoricalHigh?: T;
  shooterClassifiersPercentHistoricalAge?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}